### ISSUE TITLE
ok to share this?

### ISSUE THREAD

**Issue by rtfeldman** [furrary/react-fiber-demo#1]
I just thought to myself "I wonder how the Sierpinski Triangle demo would do in Elm" and was searching for the React one, and this came up!

This is awesome - thank you so much for making it!

Would it be okay with you if I shared it? (I infer from commit frequency that it's currently under active development. 😄)

**Comment by furrary** [comment]
Of course 😀

I've just started learning Elm 4 days ago and I made this since I was wondering the same thing.

BTW, didn't expect to hear from you.

**Comment by rtfeldman** [comment]
Wow, I'm really impressed that you put this together with only 4 days of Elm experience - way to go! 🎉 🎉 🎉

I shared it on Elm Slack here: https://elmlang.slack.com/archives/C0K384K4Y/p1511882521000305

I don't know if you've found Elm Slack yet, but it's really great! http://elmlang.herokuapp.com/
